### ISSUE TITLE
[SubTask]docsCreation : 4. 系統架構書撰寫

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/KnowledgeManagement#69]
- [x] 功能需求
- [x] 架構圖

**Comment by Julian0701** [comment]
- take 8 hrs, remain 1 hr
- [ ] 系統微服務架構

**Comment by godmmt** [comment]
等妳完成後～
請於 [新手指南目錄](https://github.com/CAFECA-IO/WorkGuidelines/tree/main/newbie/software-engineering) 底下新增文件

- 文件名稱：

  ```
  04-system-architecture-documentation.md
  ```

- 文件內容：妳撰寫的本文，直接貼上即可。

**Comment by Julian0701** [comment]
- take 1 hr
- done
- [系統架構書](https://github.com/CAFECA-IO/WorkGuidelines/blob/main/newbie/software-engineering/04-system-architecture-documentation.md)

**Comment by godmmt** [comment]
拍謝，麻煩幫我把文件名稱改為：
```
04-system-architecture-document-writing.md
```
(這樣作者才確保是妳 XD 不然會被我偷走)
