### ISSUE TITLE
[SubTask]docsCreation : 9. 版本管理

### ISSUE THREAD

**Issue by godmmt** [CAFECA-IO/KnowledgeManagement#74]
- [x] 版本管理的定義
- [x] 歷史
- [x] 工具

**Comment by godmmt** [comment]
# 版本管理

## 什麼是版本管理
版本管理是一個重要的程式開發概念，用於追蹤和控制程式碼的變化。

在程式開發中，我們使用版本控制系統 (Version Control System, VCS) 來**管理**程式碼的不同**版本**，也就是利用版本控制來追蹤、維護原始碼 (Source code)、檔案 (file) 以及設定檔 (configuration file) 等的改動。

所以說，當我們討論到「版本管理」，也就是在討論「版本控制」，在這裡我們可以先將兩者視為同樣意涵的用詞。

### 版本控制(版控)

如果我們想要避免資料不見的風險，我們就會進行備份。有了備份，就有辦法還原，即便是電腦中毒掛了，只要備份還在，就能夠把以前的資料拿回來。這種概念就是最原始的版控系統，VCS (Version Control System)。但如果我們只在本地端 (自己的電腦上) 備份並控管，一旦本地設備出狀況就會血本無歸。

同樣道理，公司裡儲存大型數據的資料庫，或是開發部門的專案，也需要備份。對於公司而言，維持這些資料的完整可說是至關重要，千萬不能有「一跳電資料就全部消失還原不了」這類情況發生。

但除了備份之外，如果要在公司中使用，我們還得實現一個功能 ——「共用」。

想像一下，在一間 100 人的小公司裡，一次只有一台電腦能連上資料庫，如果遇到問題需要更改，就得排隊排好長一段時間，等到排到時可能問題已經擴散到其他檔案了...

為了方便多人共用，便出現了備份 x 共用的版控，CVCs (Centralized Version Control System)，比起 VCS，可以接受多人共同使用，但還是繼承了上一代的缺點，只要本地設備一出狀況，就會血本無歸。

### Git 與版本控制

世界上有很多版本控制系統可供選擇，其中一個常見的是Git。Git讓我們可以追蹤程式碼的變化、合併不同的版本。我們可以建立不同的分支來進行實驗、修復錯誤，最終將它們合併到主分支中。這有助於確保團隊協作的順暢，最重要的是它同時提供了一個完整的版本歷史記錄。

Git 與其他版控系統最大的差異就於，它解決了「單一儲存區」這項最致命的缺點，改為「分散式儲存」， DVCs (Distributed Version Control System)。DVSs 將資料分散於不同設備上 (就是儲存資料的本地端)，如此一來，就算其中一處設備損壞，也不影響其他用戶使用。

GitHub 便是採用 Git 的理念，除了專案作者本人的電腦上，也在 GitHub 官網上儲存一份備份，而且每個曾進行過更動的本地端 (就是改過檔案的人的電腦) 也能重新放回官網上，形成新的備份。

<--! Git 小故事要放嗎-->

## 透過 GitHub 實現版本控制

GitHub 是一個「透過 Git 進行版本控制」的「原始碼代管服務平台」。
<--! -->

**Comment by godmmt** [comment]
took 3 hours

done.

**Comment by godmmt** [comment]
took 3 hours

done.

**Comment by Luphia** [comment]
補充一個小故事，早在 20 年前版本控管還不普及的年代，有一個開發團隊使用 ftp 進行版本控管，每週五將程式碼 zip 後加上日期保管。有一天每個倒霉的工程師 Babu 與伴侶發生了嚴重的爭執，對方一氣之下半夜把 Babu 電腦上的檔案通通刪除，連同團隊的 ftp 以及四個月的肝指數結晶一起灰飛煙滅...

**Comment by godmmt** [comment]
sad story... 🥲

> 補充一個小故事，早在 20 年前版本控管還不普及的年代，有一個開發團隊使用 ftp 進行版本控管，每週五將程式碼 zip 後加上日期保管。有一天某個倒霉的工程師 Babu 與伴侶發生了嚴重的爭執，對方一氣之下半夜把 Babu 電腦上的檔案通通刪除，連同團隊的 ftp 以及四個月的肝指數結晶一起灰飛煙滅...
