### ISSUE TITLE
[KM] UX Research- User Flow 及 function Map

### ISSUE THREAD

**Issue by JodieWu** [CAFECA-IO/KnowledgeManagement#83]
- 根據使用者調查尋求解決方案並創建 Function Map

- 跟據 Function Map 創建每個情境下的 User Flow

- 從 User Flow 及 Function Map 中產出系統架構書

**Comment by StrawHo** [comment]
LINK:
https://github.com/CAFECA-IO/KnowledgeManagement/blob/master/UX/user%20flow.md

花費時間約8hr
